### ISSUE TITLE
Cannot get the library to work

### ISSUE THREAD

**Issue by khill-fbmc** [TypeAI-dev/typeai#4]
I have tried to get the first example from the README working, but have been running into issues. [Here is a repo I made to reproduce my issue](https://github.com/khill-fbmc/typeai-bug-repo)

I installed the dependencies, yet still face this when trying to run.

![image](https://github.com/TypeAI-dev/typeai/assets/107003416/626e936c-5aa4-411b-ae28-1a818976ff96)

**Comment by jefflaporte** [comment]
@khill-fbmc Thanks for reporting this, I typo'd the install instructions 🤦 

Fixed here: https://github.com/TypeAI-dev/typeai/commit/3daf292bcba0b87fae22e51cce339affe7935b3e

Instructions should be:

```sh
npm install @typeai/core @deepkit/core
npm install @deepkit/type@npm:@jefflaporte/deepkit-type@1.0.1-alpha.97-jl      # fixed line
npm install --save-dev @deepkit/type-compiler@npm:@jefflaporte/deepkit-type-compiler@1.0.1-alpha.97-jl     # fixed line
./node_modules/.bin/deepkit-type-install
```

Let me know if you have any other trouble!

**Comment by jefflaporte** [comment]
@khill-fbmc I should also mention - I notice your test repo used typescript "^5.1.6". TypeAI is using 4.8.4, but only because that is what Deepkit 1.0.1-alpha.97 is using, and I haven't tested much with other typescript versions. I did test with 4.9 earlier and it was probably working, but I got strict for a while about matching Deepkit's deps for simplicity.

**Comment by jefflaporte** [comment]
Hey @khill-fbmc, just to give a heads up I have a fix for this but I'm going to push it with some other new things, probably later this afternoon or tonight. Thanks for posting your repo!

**Comment by jefflaporte** [comment]
@khill-fbmc Ok, there were a couple things going on:
* Fixes to aiFunction for certain cases, available in v0.6.1
* It turns out `tsx` doesn't work with Deepkit. Deepkit injects it's type compiler transform by modifying tsc. It seems the method tsx uses to build doesn't execute the injected transform. After changing your test repo to use `ts-node-esm` it works for me now.

**Comment by khill-fbmc** [comment]
Very interesting find! I have no idea how `tsx` works (or the typescript internals for that matter), so I trust you :)

I will test later and report back

**Comment by khill-fbmc** [comment]
👆👆👆👆👆👆👆👆

🥳

[I swapped `tsx` for `ts-node` like you suggested](https://github.com/khill-fbmc/typeai-bug-repo/blob/main/package.json#L8)

[I also added `dotenv` to load the api key from my file instead of the CLI](https://github.com/khill-fbmc/typeai-bug-repo/blob/main/index.ts#L1)
